---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  annotations:
    fabric8.io/iconUrl: "img/icons/vertx.svg"
    fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=piza&var-version=v1"
  labels:
    provider: "fabric8"
    project: "piza"
    version: "v1"
    group: "zomato"
  name: "piza"
spec:
  replicas: 1
  selector:
    matchLabels:
      project: "piza"
      provider: "fabric8"
      group: "zomato"
  template:
    metadata:
      annotations:
        fabric8.io/iconUrl: "img/icons/vertx.svg"
        fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=piza&var-version=v1"
      labels:
        provider: "fabric8"
        project: "piza"
        version: "v1"
        group: "zomato"
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "zomato/piza:v1"
        imagePullPolicy: "IfNotPresent"
        name: "java-exec"
        ports:
        - containerPort: 9779
          name: "prometheus"
          protocol: "TCP"
        - containerPort: 8778
          name: "jolokia"
          protocol: "TCP"
        securityContext:
          privileged: false
